# Generated by Django 4.2.1 on 2023-05-27 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contol_estudios', '0010_alter_post_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='fecha',
        ),
    ]
